# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:

        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [205, 100]
                    mode:          outbound
                    allow_upscale: true

        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [348, 182]
                    mode:          outbound
                    allow_upscale: true

        home_thumbnail_large:
            filters:
                thumbnail:
                    size:          [384, 225]
                    mode:          outbound
                    allow_upscale: true

        trick_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [400, 240]
                    mode:          outbound
                    allow_upscale: true

        user_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [246, 246]
                    mode:          outbound
                    allow_upscale: true

        user_thumbnail_small:
            filters:
                thumbnail:
                    size:          [80, 80]
                    mode:          outbound
                    allow_upscale: true